import 'package:flutter/material.dart';

/// CNG LIVE — Animated Splash Screen
///
/// Shown immediately after the native (platform-drawn) splash screen
/// generated by `flutter_native_splash` hands off to Flutter. The native
/// splash covers the gap between process start and the first Flutter
/// frame (logo on brand background, no animation possible there); this
/// widget takes over from that same look and adds the fade-in, the
/// "CNG LIVE" / tagline / loading copy, and the animated three-dot
/// loader, then navigates to [nextRoute] once [duration] elapses.
///
/// [nextRoute] is the route `main.dart` already resolved before
/// `runApp` (`/home` if a driver session exists, otherwise `/login`) —
/// this widget only owns the splash presentation, not auth logic.
class SplashScreen extends StatefulWidget {
  const SplashScreen({
    super.key,
    required this.nextRoute,
    this.duration = const Duration(seconds: 2),
  });

  final String nextRoute;
  final Duration duration;

  static const Color backgroundColor = Color(0xFF0F3D0F);
  static const Color taglineColor = Color(0xFF8BE28A); // light green
  static const Color dotColor = Color(0xFF3DDC5A); // green

  @override
  State<SplashScreen> createState() => _SplashScreenState();
}

class _SplashScreenState extends State<SplashScreen>
    with TickerProviderStateMixin {
  late final AnimationController _fadeController;
  late final Animation<double> _logoFade;
  late final Animation<double> _logoScale;
  late final Animation<double> _textFade;

  late final AnimationController _dotsController;

  @override
  void initState() {
    super.initState();

    // 1) Logo fade-in (+ a subtle scale-up so it doesn't feel static).
    _fadeController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 700),
    );
    _logoFade = CurvedAnimation(
      parent: _fadeController,
      curve: const Interval(0.0, 0.7, curve: Curves.easeOut),
    );
    _logoScale = Tween<double>(begin: 0.85, end: 1.0).animate(
      CurvedAnimation(
        parent: _fadeController,
        curve: const Interval(0.0, 0.7, curve: Curves.easeOutBack),
      ),
    );
    // Title / tagline / "Loading..." fade in slightly after the logo.
    _textFade = CurvedAnimation(
      parent: _fadeController,
      curve: const Interval(0.35, 1.0, curve: Curves.easeOut),
    );
    _fadeController.forward();

    // 2) Three-dot loader: ● ○ ○ → ● ● ○ → ● ● ● → repeat.
    _dotsController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 900),
    )..repeat();

    // 3) Fixed-duration splash, then hand off to the real first screen.
    Future.delayed(widget.duration, () {
      if (!mounted) return;
      Navigator.of(context).pushReplacementNamed(widget.nextRoute);
    });
  }

  @override
  void dispose() {
    _fadeController.dispose();
    _dotsController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: SplashScreen.backgroundColor,
      body: SafeArea(
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const Spacer(flex: 3),
              FadeTransition(
                opacity: _logoFade,
                child: ScaleTransition(
                  scale: _logoScale,
                  child: Image.asset(
                    'assets/images/splash_logo.png',
                    width: 176,
                    height: 176,
                  ),
                ),
              ),
              const SizedBox(height: 28),
              FadeTransition(
                opacity: _textFade,
                child: const Text(
                  'CNG LIVE',
                  style: TextStyle(
                    fontSize: 30,
                    fontWeight: FontWeight.bold,
                    color: Colors.white,
                    letterSpacing: 1.2,
                  ),
                ),
              ),
              const SizedBox(height: 10),
              FadeTransition(
                opacity: _textFade,
                child: const Text(
                  'Real-Time CNG Updates',
                  style: TextStyle(
                    fontSize: 15,
                    fontWeight: FontWeight.w500,
                    color: SplashScreen.taglineColor,
                    letterSpacing: 0.4,
                  ),
                ),
              ),
              const Spacer(flex: 3),
              FadeTransition(
                opacity: _textFade,
                child: Text(
                  'Loading...',
                  style: TextStyle(
                    fontSize: 14,
                    color: Colors.white.withOpacity(0.7),
                  ),
                ),
              ),
              const SizedBox(height: 14),
              FadeTransition(
                opacity: _textFade,
                child: _LoadingDots(controller: _dotsController),
              ),
              const SizedBox(height: 40),
            ],
          ),
        ),
      ),
    );
  }
}

/// Three dots that fill in left-to-right on a repeating cycle:
/// ● ○ ○ → ● ● ○ → ● ● ● → (repeat). Each dot's fill fades in/out
/// smoothly rather than snapping, driven by a single looping
/// [controller] so the three dots stay in sync.
class _LoadingDots extends StatelessWidget {
  const _LoadingDots({required this.controller});

  final AnimationController controller;

  @override
  Widget build(BuildContext context) {
    return AnimatedBuilder(
      animation: controller,
      builder: (context, _) {
        // Split one full loop into 3 equal steps. Step index tells us
        // how many dots are "on" (1, 2, then 3); the fractional part
        // within the current step drives a smooth per-dot fade.
        final t = controller.value * 3; // 0.0 .. 3.0
        final step = t.floor().clamp(0, 2); // 0, 1, or 2
        final localT = (t - step).clamp(0.0, 1.0); // progress within step

        return Row(
          mainAxisSize: MainAxisSize.min,
          children: List.generate(3, (i) {
            double opacity;
            if (i < step) {
              // Already fully on from an earlier step.
              opacity = 1.0;
            } else if (i == step) {
              // The dot turning on during this step.
              opacity = localT;
            } else {
              // Not yet reached.
              opacity = 0.0;
            }
            return Padding(
              padding: const EdgeInsets.symmetric(horizontal: 5),
              child: Opacity(
                opacity: 0.25 + (opacity * 0.75),
                child: Container(
                  width: 10,
                  height: 10,
                  decoration: const BoxDecoration(
                    color: SplashScreen.dotColor,
                    shape: BoxShape.circle,
                  ),
                ),
              ),
            );
          }),
        );
      },
    );
  }
}
